/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zjf_ffmpegdecoder_FFmpeg */

#ifndef _Included_com_example_zjf_ffmpegdecoder_FFmpeg
#define _Included_com_example_zjf_ffmpegdecoder_FFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zjf_ffmpegdecoder_FFmpeg
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_zjf_ffmpegdecoder_FFmpeg_decode
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_zjf_ffmpegdecoder_FFmpeg
 * Method:    play
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_example_zjf_ffmpegdecoder_FFmpeg_play
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
